name: client
version: 0.0.1
description: noBS client
dependencies:
  browser: any
  intl: any
  angular: any
  logging: any
  rate_limit: any
  quiver: any
dev_dependencies:
  unittest: any
  typed_mock: any
  script_inliner: any
  args: any
  path: any
  barback: any
  appcache: any
transformers:
- script_inliner
- angular:
    $exclude: test
- appcache:
    $exclude: ["**.dart", "**.less", "**.html_reference"]
    entry_points: web/client.html
    cache:
      - web/client.dart.js

- client/client_version_patcher:
    entryPoint: client.dart