name: client
version: 0.0.1
description: noBS client
dependencies:
  browser: any
  intl: any
  angular: any
  logging: any
  rate_limit: any
  quiver: any
dev_dependencies:
  unittest: any
  typed_mock: any
  script_inliner: any
  args: any
  path: any
  barback: any
transformers:
- script_inliner
- angular:
    $exclude: test
- client/client_version_patcher:
    entryPoint: client.dart