name: client
version: 0.0.1
description: noBS client
dependencies:
  browser: any
  intl: any
  angular: any
  logging: any
  rate_limit: any
dev_dependencies:
  unittest: any
  typed_mock: any
  grinder: any
  nvp:
    git:
      url: git://github.com/bgourlie/nobsVersionPatcher.git
      ref: master
transformers:
- angular
- nvp/client_version_patcher:
    entryPoint: client.dart