language: csharp
os: linux
env:
  global:
  - "AZURE_FTP_USER=nobs-api\\\\nobs_deploy"
  - DART_DIST=dartsdk-linux-x64-release.zip
  - DART_SDK=~/dart-sdk
  - KRE_HOME=~/.kre/packages/KRE-Mono.1.0.0-beta1
  - PATH="$DART_SDK/bin:$KRE_HOME/bin:$PATH"
  - DEPLOY_BRANCH=master
  - BUILD_TIME=$(date -Iseconds)
    # AZURE_FTP_PASSWORD
  - secure: "GJaru0tQx5/kubON7FZ1GeSP9qv1qezC8Nj+XedrUPBf/SjJTdiTKVQ5J4DBYG/MbvL3W/H2EnVBc6F6C4zfYJX6HRIlueaRX4FF4tsHUaOVnS8pBBnu6XJLPRwDsfuboxhXVfImZOUu2mkcXNbqo1Bi2fPlZwuDV/AYaMlZCSM="

notifications:
  email:
    recipients:
    - bgourlie@gmail.com
    on_success: change
    on_failure: always
before_install:
- date -u
- uname -a
- env | sort
- "./ci/install-deps.sh"
script:
- "./ci/run-tests.sh"
after_success:
- "./ci/pack-deployment.sh"
- "./ci/deploy.sh"
