language: node_js

os: linux

env:
  global:
    - DART_DIST=dartsdk-linux-x64-release.zip
    - DART_SDK=~/dart-sdk
    - MONO_HOME=/opt/mono
    - KRE_HOME=~/.kre/packages/KRE-Mono.1.0.0-beta1
    - PATH="$DART_SDK/bin:$MONO_HOME/bin:$KRE_HOME/bin:$PATH"

notifications:
  email:
    recipients:
      - bgourlie@gmail.com
    on_success: change
    on_failure: always

before_install:
  - date -u
  - uname -a
  - env | sort
  - ./ci/install.dart.sh
  - ./ci/travis.${TRAVIS_OS_NAME}.install.deps.sh

script:
  - ./ci/travis.sh

after_success:
  - ./ci/deploy-client.sh
