language: c

os:
  - linux

notifications:
  email:
    recipients:
      - bgourlie@gmail.com
    on_success: change
    on_failure: always

before_install:
  - date -u
  - uname -a
  - export PATH=/opt/mono/bin:$PATH
  - env | sort

install:
  - ./ci/travis.${TRAVIS_OS_NAME}.install.deps.sh

script:
  - ./ci/travis.sh
