language: csharp
os: linux
env:
  global:
  - "AZURE_FTP_USER=nobs-api\\\\nobs_deploy"
  - DART_DIST=dartsdk-linux-x64-release.zip
  - DART_SDK=~/dart-sdk
  - KRE_HOME=~/.kre/packages/KRE-Mono.1.0.0-beta1
  - PATH="$DART_SDK/bin:$KRE_HOME/bin:$PATH"
  - DEPLOY_BRANCH=master
  - BUILD_TIME=$(date -Iseconds)
    # AZURE_FTP_PASSWORD
  - secure: "V5lVEyfGZqG8JT0P4zbJO1aS2jLXVQKkSj42twhA0Au24ibvfEsIfI5QPqj3sY7jv2SjpNM9fg1ZHMLC/lYw+S+5a57MCDzJChguMKvFBV5FC2qyA1Q2zYANTI3JE7qA+wWmI8DaJQ3AlDSeiItQlrYKsH7gk0O9R1zCcRDXfyc="

notifications:
  email:
    recipients:
    - bgourlie@gmail.com
    on_success: change
    on_failure: always
before_install:
- date -u
- uname -a
- env | sort
- "./ci/install-deps.sh"
script:
- "./ci/run-tests.sh"
after_success:
- "./ci/pack-deployment.sh"
- "./ci/deploy.sh"
